# Conversation states
(
    AWAITING_PHOTO,
    AWAITING_CONFIRM,
    AWAITING_MANUAL_DATA,
    AWAITING_TECH_PASSPORT_1,
    AWAITING_TECH_PASSPORT_2,
    AWAITING_TECH_PASSPORT_CONFIRM,
    AWAITING_MANUAL_VEHICLE_DATA,
    AWAITING_VEHICLE_CONFIRM,
    AWAITING_AGREEMENT,
) = range(9)